### ISSUE TITLE
the re submission of the form malfunction

### ISSUE THREAD

**Issue by costezki** [costezki/fingerprinter-ui#5]
reproduce error by following steps:
1. go to stats page
2. provide a correct csv
3. press submit and wait for the result to arrive
4. press submit again [and here is the exception]

```
Exception while invoking method 'generateJSON' TypeError: Cannot read property 'value' of undefined
I20170428-16:22:13.463(2)?     at [object Object].ValidatedMethod.run (imports/mdg/validatedMethods.js:44:32)
I20170428-16:22:13.463(2)?     at ValidatedMethod._execute (packages/mdg:validated-method/validated-method.js:93:12)
I20170428-16:22:13.464(2)?     at [object Object].ValidatedMethod.connection.methods._connection$methods.(anonymous function) (packages/mdg:validated-method/validated-method.js:54:23)
I20170428-16:22:13.464(2)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1737:12)
I20170428-16:22:13.464(2)?     at packages/ddp-server/livedata_server.js:719:19
I20170428-16:22:13.464(2)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20170428-16:22:13.466(2)?     at packages/ddp-server/livedata_server.js:717:40
I20170428-16:22:13.467(2)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20170428-16:22:13.467(2)?     at packages/ddp-server/livedata_server.js:715:46
I20170428-16:22:13.467(2)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp-server/livedata_server.js:689:23)
```

**Comment by costezki** [comment]
the logic reimplemented
